### PR TITLE
arc.reputations

### PR DESCRIPTION
**Pull request by dOrgJelli**

### CODE REVIEW

**Comment by jellegerbrandy** [comment]
what problem is this PR solving? 

You can create a new reputation object by doing `new Reputation(address)`, and you can get a list of "reputationContracts" by asking forthe list of daos, and getting _their_ nativeReputation contracts...

**Comment by dOrgJelli** [comment]
Yes definitely @jellegerbrandy I see that's an option, but I was thinking that from a user's perspective it'd be nice to query all reputation tokens directly without needing the context of the DAO beforehand (as it's not a requirement).

This is more optimized if the user is only interested in aggregating information about reputation distribution, and then looking into the rest of the details of the DAO at a later time.

I can definitely see this going either way when it comes to the design, so I'm indifferent in this. I will leave it up to you and the team to either deny or accept this PR, and I can continue to build based on that decision.

**Comment by dOrgJelli** [comment]
One more thought:
Reputation Tokens are a "top level primitive" in that they do not rely on the DAO (as stated in my last comment). An example of something that is not "top level" are Members, as they require the DAO as context.

**Comment by dOrgJelli** [comment]
@jellegerbrandy quick ping on this, do you have a final opinion on this addition? I'm good with closing this PR if you'd rather only support the DAO->Reputations flow.

**Comment by jellegerbrandy** [comment]
But if you want to do data analyssis on repution holders of different DAOs, this `reputations` does not help that much, because it returns the reputation **contracts**, which you'd still need to query separate to get the list of reputation holders. (And that is why i think it does not add much useful functionality)


There is another pattern that the client library supports, whch is this pseudocode:
``` 
import Proposal 
const arc = new Arc({... settingss... }))
Proposal.search({...}, arc) // this will search the whole subraph for proposals, along all DAOs
```

And we could imagine implementing that same pattern for the `Member ` class, so you can get all members of all daos... 

Do you have  a specific use case, btw?

**Comment by dOrgJelli** [comment]
Okay awesome, thanks @jellegerbrandy for the feedback & additional context. I've created this PR to replace this one: https://github.com/daostack/client/pull/210

**Pull request closed without merging**
